name = "Transits"
uuid = "2e59a628-7bac-4d38-8059-3a73ba0928ab"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.3"
